{"uuid":"723260b5-b214-4e67-8346-688043e105e2","historyId":"e4f54f3868232cc2a9913280b6f88dd5","fullName":"Array: The user is able to submit code in tryEditor for Max Consecutive Ones","labels":[{"name":"tag","value":"arrays"},{"name":"tag","value":"scenario_011"},{"name":"host","value":"DESKTOP-RGL4EEL"},{"name":"thread","value":"12832@DESKTOP-RGL4EEL.main(1)"},{"name":"feature","value":"Array"},{"name":"story","value":"The user is able to submit code in tryEditor for Max Consecutive Ones"},{"name":"suite","value":"Array"},{"name":"testClass","value":"The user is able to submit code in tryEditor for Max Consecutive Ones"},{"name":"framework","value":"cucumber4jvm"},{"name":"language","value":"java"},{"name":"gherkin_uri","value":"file:///C:/Users/janga/eclipse-workspace/DSAlgosample/src/test/resources/Features/UC05_Arrays.feature"},{"name":"package","value":"src.test.resources.Features.UC05_Arrays_feature.Array"}],"links":[],"name":"The user is able to submit code in tryEditor for Max Consecutive Ones","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Result do not match expected [submission success] but found [ Some Tests failed. Please review code]","trace":"java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:629)\r\n\tat com.Stepdefinitions.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:139)\r\n\tat ✽.The user should be presented with successful submission message(file:///C:/Users/janga/eclipse-workspace/DSAlgosample/src/test/resources/Features/UC05_Arrays.feature:138)\r\n"},"stage":"finished","steps":[{"name":"Given  The user is on \"Question\" page of \"Max Consecutive Ones\" after logged in","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1680050502343,"stop":1680050502473},{"name":"When  The user enter valid python code in tryEditor from sheet \"pythonCode\" and 5 for the question","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1680050502474,"stop":1680050504222},{"name":"And  The user clicks on Submit button","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1680050504223,"stop":1680050504277},{"name":"Then  The user should be presented with successful submission message","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Result do not match expected [submission success] but found [ Some Tests failed. Please review code]","trace":"java.lang.AssertionError: Result do not match expected [submission success] but found [ Some Tests failed. Please review code]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:629)\r\n\tat com.Stepdefinitions.ArraysStepDef.the_user_should_be_presented_with_successful_submission_message(ArraysStepDef.java:139)\r\n\tat ✽.The user should be presented with successful submission message(file:///C:/Users/janga/eclipse-workspace/DSAlgosample/src/test/resources/Features/UC05_Arrays.feature:138)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1680050504277,"stop":1680050504860}],"attachments":[],"parameters":[{"name":"Sheetname","value":"pythonCode"},{"name":"RowNumber","value":"5"}],"start":1680050502343,"stop":1680050505492}